#!/bin/bash

echo "----------------------------------------------------"
read -p "[INPUT] Enter your email for the auto-save: " AUTO_EMAIL
echo "$AUTO_EMAIL" > /tmp/auto_email
echo "----------------------------------------------------"

echo "[SYSTEM] Killing Processes..."
sudo pkill -9 -f qemu-system-x86_64 2>/dev/null
sudo pkill -9 -f websockify 2>/dev/null
sudo pkill -9 -f stunnel4 2>/dev/null
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null

if [ ! -f "/tmp/windows/methalo.vhdx" ]; then
    echo "----------------------------------------------------"
    echo "[SYSTEM] No VM found. Downloading default Windows..."
    echo "----------------------------------------------------"
    sudo mkdir -p /tmp/windows
    sudo curl -L -o /tmp/windows/methalo.vhdx "https://pub-dc6f3e26ce5940dd92d9c742a92d150e.r2.dev/methalo.vhdx"
    sudo chmod -R 777 /tmp/windows
fi

echo "[SYSTEM] Starting HTTPS Bridge (Port 8008)..."
sudo stunnel4 /etc/stunnel/myrtille.conf
sudo cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html 2>/dev/null
sudo /usr/bin/websockify --web /usr/share/novnc/ 8006 localhost:5900 >/dev/null 2>&1 &
sleep 2

echo "[SYSTEM] Booting Windows..."
sudo qemu-system-x86_64 \
  -m 5G \
  -smp 2 \
  -enable-kvm \
  -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
  -drive file=/tmp/windows/methalo.vhdx,format=vhdx,cache=writeback,aio=threads \
  -netdev user,id=net0,hostfwd=tcp::8008-:80 \
  -device e1000,netdev=net0 \
  -vnc :0 \
  -vga none \
  -device virtio-vga \
  -device usb-ehci,id=usb,bus=pci.0,addr=0x7 \
  -device usb-tablet \
  -audiodev none,id=none &
