#!/bin/bash
for i in {1..36}; do
    sleep 900
    echo -n . >> /tmp/autobackup.log
    
    # Run cache clear every time a dot appears
    sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null

    if [ $i -eq 32 ]; then
        echo >> /tmp/autobackup.log
        echo "[BACKUP] 8 Hours reached. Starting automatic backup..." >> /tmp/autobackup.log
        vm-export auto >> /tmp/autobackup.log 2>&1
    fi
done
