#!/bin/bash
sudo pkill -9 -f qemu-system-x86_64 2>/dev/null
sudo pkill -9 -f websockify 2>/dev/null
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null

echo "[SYSTEM] Starting Debug Console..."
sudo cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html 2>/dev/null
sudo /usr/bin/websockify --web /usr/share/novnc/ 8006 localhost:5900 >/dev/null 2>&1 &

echo "[SYSTEM] Booting Methalo Myrtille..."
sudo qemu-system-x86_64 \
  -m 11G \
  -smp 4 \
  -enable-kvm \
  -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
  -drive file=/tmp/windows/methalo.vhdx,format=vhdx,cache=writeback,aio=threads \
  -netdev user,id=net0,hostfwd=tcp::8443-:8443 \
  -device e1000,netdev=net0 \
  -vnc :0 \
  -vga none \
  -device virtio-vga \
  -device usb-ehci,id=usb,bus=pci.0,addr=0x7 \
  -device usb-tablet \
  -audiodev none,id=none
