#!/bin/bash
echo "[SYSTEM] Starting noVNC Console..."
# Added 'index.html' redirect to vnc.html
cp /usr/share/novnc/vnc.html /usr/share/novnc/index.html
/usr/bin/websockify --web /usr/share/novnc/ 8006 localhost:5900 &

echo "[SYSTEM] Booting Windows..."
sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
sudo qemu-system-x86_64 \
  -m 6G \
  -smp 2 \
  -enable-kvm \
  -cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
  -drive file=/tmp/windows/data.vhdx,format=vhdx,cache=writeback,aio=threads \
  -netdev user,id=net0,hostfwd=tcp::8443-:8443 \
  -device virtio-net-pci,netdev=net0 \
  -vga std \
  -vnc :0 \
  -audiodev none,id=none \
  -device intel-hda -device hda-duplex